name: disruption-tracker
version: 0.0.1.0
synopsis: Track TfL disruptions
description: Please see README.md
homepage: http://github.com/passy/disruption-tracker
license: BSD3
author: Pascal Hartig
maintainer: Pascal Hartig <phartig@rdrei.net>
category: Web
extra-source-files:
  - stack.yaml
  - README.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text

library:
  source-dirs: src
  dependencies:
    - text
    - optparse-applicative
    - bytestring
    - lens
    - wreq
    - transformers
    - aeson
    - aeson-casing
    - rethinkdb
    - data-default
  exposed-modules:
    - Lib
    - Citymapper.Types

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - disruption-tracker
      - aeson
      - basic-prelude
      - bytestring
      - containers
      - directory
      - hspec
      - hspec-expectations-lens
      - lens

executables:
  disruption-tracker:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - disruption-tracker
      - optparse-applicative
      - bytestring
      - lens
      - wreq
      - transformers
      - aeson
      - aeson-casing
      - rethinkdb
      - data-default
    other-modules:
      - Paths_disruption_tracker
